<?php
/**
 * @var \Digibart\MessagesNotification\Block\Notifications $block
 */
?>
<?php if($block->isModuleEnabled() && $block->isInboxEnabled() && $block->isLoggedIn()) :?>
<div id="inbox" class="inbox-wrapper" data-bind="scope:'inbox'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#inbox": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "inbox": {
                        "component": "Digibart_MessagesNotification/js/component/inbox",
                        "template" : "Digibart_MessagesNotification/inbox",
                        "identifier": "<?php echo $block->getIdentifier(); ?>",
                        "options": <?php echo $block->getJsonOptions() ;?>,
                        "elementId":"#inbox"
                    }
                }
            }
        }
    }
    </script>
</div>
<?php endif; ?>
