<?php
/**
 * @var \Digibart\Notifications\Block\Notifications $block
 */
?>
<?php if($block->isModuleEnabled() && $block->isNotificationEnabled() && $block->isLoggedIn()) :?>
<div id="notifications" class="notifications" data-bind="scope:'notifications'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#notifications": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "notifications": {
                        "component": "Digibart_Notifications/js/component/notifications",
                        "template" : "Digibart_Notifications/notifications",
                        "identifier": "<?php echo $block->getIdentifier(); ?>",
                        "options": <?php echo $block->getJsonOptions() ;?>
                    }
                }
            }
        }
    }
    </script>
</div>
<?php endif; ?>
